feat: use spec "x-cli-lookup" to convert server name to ID
binarylane/binarylane-cli pull request #11
Opened 2023-02-20 00:39 UTC by nats

Draft because:
- one or two refactoring should be broken out into prerequisite PR (e.g. `ListRunner.response` is now statically typed via code generation)
- requires unpublished spec changes
- the lookup mechanic inside binarylane.console.parser  should be called via argparse.Action ?

2023-04-01 02:58 UTC, nats commented
You currently just have to 'know' this is supported, since the displayed help for `server_id` is pulled from the OpenAPI spec:

```
$ grep '"server_id"' -A 4 src/binarylane/console/commands/api/* | grep -oP "description=.*" | sort | uniq -c
    1 description="""The ID of the server for which actions should be listed.""",
      1 description="""The ID of the server for which advanced features should be listed.""",
      1 description="""The ID of the server for which backups should be listed.""",
      1 description="""The ID of the server for which console URLs will be fetched.""",
      1 description="""The ID of the server for which firewall rules should be listed.""",
      1 description="""The ID of the server for which kernels should be listed.""",
      1 description="""The ID of the server for which snapshots should be listed.""",
      1 description="""The ID of the server for which software should be fetched.""",
      1 description="""The ID of the server for which the action should be fetched.""",
      1 description="""The ID of the server for which the backup is to be uploaded.""",
      1 description="""The ID of the server for which threshold alerts should be fetched.""",
      1 description="""The ID of the server for which userdata should be fetched.""",
     41 description="""The ID of the server on which the action should be performed.""",
      1 description="""The ID of the server to be cancelled.""",
      1 description="""The ID of the server to fetch.""",
      6 description="""The target server id.""",
```

@david-pershouse not sure how best to address that, any thoughts?

2023-04-04 00:56 UTC, david-pershouse requested changes
The _context passed to create_client in the lookup operations doesn't have the correct config. If I pass `--context dev` on the command line, the lookup runner ignores it and hits api.binarylane.com to resolve the name, then actual requested command executes against the dev context as expected.

2023-04-17 23:34 UTC, david-pershouse reviewed
Nice clean solution, confirms it fixes it here

2023-04-20 02:58 UTC, nats commented on templates/endpoint_module/create_mapping.jinja
> +        {% if lookup_endpoint %}
just a derp it seems while doing the id or name stuff.

2023-04-20 03:15 UTC, david-pershouse approved these changes

2023-04-20 23:52 UTC, merged